import { Inter } from 'next/font/google';
import './globals.css';
import "../lib/fontawesome";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create.xyz App',
  description: 'Generated by create.xyz',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Font Awesome CDN link goes here */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
