import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faHeartbeat,
  faUser,
  faIdCard,
  faMapMarkerAlt,
  faQrcode,
  faExclamationTriangle,
  faInfoCircle,
  faCheckCircle,
  faCircle,
  faCamera,
  faTrash,
  faDownload,
  faChevronRight,
  faLocationArrow,
  faThermometerHalf,
  faLungs,
  faCircleNotch,
  faExclamationCircle,
  faPlus,
  faSave,
  faEdit,
  faExternalLinkAlt,
} from "@fortawesome/free-solid-svg-icons";

// Register only the icons you use
library.add(
  faHeartbeat,
  faUser,
  faIdCard,
  faMapMarkerAlt,
  faQrcode,
  faExclamationTriangle,
  faInfoCircle,
  faCheckCircle,
  faCircle,
  faCamera,
  faTrash,
  faDownload,
  faChevronRight,
  faLocationArrow,
  faThermometerHalf,
  faLungs,
  faCircleNotch,
  faExclamationCircle,
  faPlus,
  faSave,
  faEdit,
  faExternalLinkAlt
);
